accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('setting/', views.setting, name='setting'),

    # API
    path('api/signup/', views.UserSignUpView.as_view(), name='api_signup'),
    path('api/login/', views.UserLogInView.as_view(), name='api_login'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('wordle/', include('wordle.urls')),
    path('accounts/', include('accounts.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('', include('town.urls')),
    path('backender/', include('backender.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

game/urls.py
from django.urls import path
from . import views
app_name = 'game'

urlpatterns = [
    path('', views.index, name='index'),
    path('test', views.test, name='test'),
]

wordle/urls.py
from django.urls import path
from . import views
app_name = 'wordle'

urlpatterns = [
    path('', views.index, name='main'),
    path('stats', views.stats, name='stats'),
    path('leaderboard', views.leaderboard, name='leaderboard'),

    # API
    path('api/', views.WordAPIView.as_view(), name='word')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.utils import timezone
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, username, password, email=None, **extra_fields):
        if not username:
            raise ValueError('Username을 입력해주세요.')
        print(username)
        username = self.model.normalize_username(username)
        print(username)
        if email:
            email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)
        return user
    
    def create_user(self, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, password, **extra_fields)

    def create_superuser(self, username, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('is_staff=True일 필요가 있습니다.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('is_superuser=True일 필요가 있습니다.')
        return self._create_user(username, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(_("username"), max_length=50, validators=[username_validator], unique=True)
    email = models.EmailField(_("email"),max_length=255,unique=True,null=True)
    is_staff = models.BooleanField(_("staff status"), default=False)
    is_active = models.BooleanField(_("active"), default=True)
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
    last_login = models.DateTimeField(_("last_login"), default=timezone.now)

    plays = models.PositiveIntegerField(_("plays"), default=0)  # 게임수
    wins = models.PositiveIntegerField(_("wins"), default=0)    # 이긴횟수
    tries = models.PositiveBigIntegerField(_("tries"), default=0)   # 총시도수

    objects = UserManager()
    USERNAME_FIELD = "username"
    # REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()

accounts/views.py
import jwt

from django.shortcuts    import render, get_object_or_404
from django.urls         import reverse
from django.contrib.auth import authenticate
from django.utils        import timezone

from rest_framework             import generics, status
from rest_framework.views       import APIView
from rest_framework.response    import Response
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer

from config.settings import SECRET_KEY

from .serializer import *

def setting(request):
    return render(request, 'accounts/setting.html')

def login(request):
    return render(request, 'accounts/login.html')

class UserSignUpView(APIView):
    def post(self, request):
        serializer = UserSerializer(data=request.data)
        if serializer.is_valid():
            user = serializer.save()
            
            index_url = reverse('wordle:main')
            # jwt 토큰 접근
            token = TokenObtainPairSerializer.get_token(user)
            refresh_token = str(token)
            access_token = str(token.access_token)
            res = Response(
                {
                    "user": serializer.data,
                    "message": "register successs",
                    "token": {
                        "access": access_token,
                        "refresh": refresh_token,
                    },
                },
                # status=status.HTTP_200_OK,
                status=status.HTTP_302_FOUND,
                headers={'Location': index_url}
            )
            
            # jwt 토큰 => 쿠키에 저장
            res.set_cookie("access", access_token, httponly=True)
            res.set_cookie("refresh", refresh_token, httponly=True)
            
            return res
        
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def delete(self, request):
        try:
            if 'access' not in request.COOKIES:
                return Response(status=status.HTTP_204_NO_CONTENT)
            access = request.COOKIES['access']
            payload = jwt.decode(access, SECRET_KEY, algorithms=['HS256']) # 토큰 디코드
            pk = payload.get('user_id') 
            user = get_object_or_404(User, pk=pk) # id 로 유저 받아옴
            user.delete()
            res = Response({'message': 'withdrawal success'}, status=status.HTTP_200_OK)
            res.delete_cookie('access')
            res.delete_cookie('refresh')
            return res
        except:
            return Response(status=status.HTTP_400_BAD_REQUEST)
    

class UserLogInView(APIView):
    # 유저 정보
    def get(self, request):
        try:
            # access token decode
            if 'access' not in request.COOKIES:
                return Response(status=status.HTTP_204_NO_CONTENT)
            access = request.COOKIES['access']
            payload = jwt.decode(access, SECRET_KEY, algorithms=['HS256']) # 토큰 디코드
            pk = payload.get('user_id') 
            user = get_object_or_404(User, pk=pk) # id 로 유저 받아옴
            serializers = UserSerializer(instance=user)
            return Response(serializers.data, status=status.HTTP_200_OK)
            
        except(jwt.exceptions.ExpiredSignatureError): # 토큰 만료
            data = {'refresh': request.COOKIES.get('refresh',None)}
            serializer = TokenObtainPairSerializer(data=data)
            if serializer.is_valid(raise_exception=True):
                access = serializer.data.get('access',None)
                refresh = serializer.data.get('refresh', None)
                payload = jwt.decode(access, SECRET_KEY, algorithms=['HS256'])
                pk = payload.get('user_id')
                user = get_object_or_404(User, pk=pk)
                serializer = UserSerializer(instance=user)
                res = Response(serializer.data, status=status.HTTP_200_OK)
                res.set_cookie('access', access)
                res.set_cookie('refresh', refresh)
                return res
            raise jwt.exceptions.InvalidTokenError

        except(jwt.exceptions.InvalidTokenError): # 사용 불가능한 토큰
            return Response(status=status.HTTP_400_BAD_REQUEST)
    
    # 로그인
    def post(self, request):
        user = authenticate(
            username=request.data.get('username'),
            password=request.data.get('password')
        )

        if user is not None:
            serializer = UserSerializer(user)
            
            user.last_login = timezone.now() # 로그인 시간 기록
            user.save()
            
            # jwt 토큰 접근
            token = TokenObtainPairSerializer.get_token(user)
            refresh_token = str(token)
            access_token = str(token.access_token)
            res = Response(
                {
                    'user': serializer.data,
                    'message': 'login success',
                    'token': {
                        'access': access_token,
                        'refresh': refresh_token,
                    },
                },
                status=status.HTTP_302_FOUND,
                headers={'location': reverse('wordle:main')}
            )
            # 쿠키에 jwt토큰 저장
            res.set_cookie('access', access_token, httponly=True)
            res.set_cookie('refresh', refresh_token, httponly=True)
            return res
        else:
            return Response(status=status.HTTP_400_BAD_REQUEST)
    
    # 로그아웃
    def delete(self, request):
        # print("logout")
        res = Response(
            {
                'message': 'Logout success'
            }, 
            status=status.HTTP_202_ACCEPTED,
        )
        res.delete_cookie('access')
        res.delete_cookie('refresh')
        return res

templates/accounts/login.html
{% load static %}
<!doctype html>
<html lang="ko">

<head>
    <title>Wordle - Account</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{% static 'img/favicon_wordle(32x32).png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/wordle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
</head>

<body>
    <div id="container">
        <header>
            {% include 'sidemenu.html' %}

            <h1 class="title">ACCOUNT</h1>

            <div id="menu">
                <a class="menu-icon" href="{% url 'wordle:main' %}">&#9989; Wordle</a>
            </div>
        </header>

        <div>
            <br>
            <h2>
                <p>LOG IN</p>
            </h2>
            <div>
                <form name="login" action="{% url 'accounts:api_login' %}" method="post">
                    {% csrf_token %}
                    <input type="text" placeholder="username" id="username" name="username" required>
                    <input type="password" placeholder="password" id="password" name="password" required>
                    <button type="submit" class="button" value="login">Log In</button>
                </form>
            </div>
            <br>
            <br>
            <br>
            <h2>
                <p>SIGN UP</p>
            </h2>
            <div>
                <form name="signup" action="{% url 'accounts:api_signup' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" id="username" name="username" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" id="password" name="password" required>
                    </div>
                    <div class="form-group">
                        <label for="password_check">Confirm Password</label>
                        <input type="password" id="password_check" name="password_check" required>
                    </div>
                    <!-- 이메일 관련 기능 만들고 추가 -->
                    <!-- <div class="form-group">
                    <label for="e-mail">e-mail (optional)</label>
                    <input type="email" id="email" name="email" required>
                    <p>이메일은 선택사항입니다.</p>
                    <p>계정 분실시 확인 용도로 사용됩니다.</p>
                    </div> -->
                    <button type="submit" class="button" value="signup">Sign Up</button>
                </form>
            </div>
        </div>
    </div>
</body>

</html>

templates/accounts/setting.html
{% load static %}
<!doctype html>
<html lang="ko">

<head>
    <title>Wordle - Account</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{% static 'img/favicon_wordle(32x32).png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/wordle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
</head>

<body>
    <div id="container">

        <header>
            {% include 'sidemenu.html' %}

            <h1 class="title">ACCOUNT</h1>

            <div id="user-menu" class="user-popup">
                <a id="user-info" class="user-popup-trigger" onclick="userInfo()">&#128100; Log In</a>
                <div class="user-popup-content">
                    <a href="{% url 'accounts:setting' %}">Settings</a>
                    <a onclick="userLogout()">Logout</a>
                </div>
            </div>
        </header>

        <div>
            <br>
            <h2>
                <p>Withdrawal</p>
            </h2>
            <div>
                <div>
                    <p>계정 탈퇴하기</p>
                    <br>
                    <!-- <a id="user-info" class="user-popup-trigger" onclick="userInfo()">&#128100; Log In</a> -->
                    <button class="button" value="withdrawal" onclick="userWithdrawal()">Withdrawal</button>
                </div>
            </div>
            <br>
            <br>
            <br>
        </div>

    </div>
    <script type="text/javascript" src="{% static 'js/userinfo.js' %}"> </script>
</body>

</html>