accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('setting/', views.setting, name='setting'),

    # API
    path('api/signup/', views.UserSignUpView.as_view(), name='api_signup'),
    path('api/login/', views.UserLogInView.as_view(), name='api_login'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('wordle/', include('wordle.urls')),
    path('accounts/', include('accounts.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('', include('town.urls')),
    path('backender/', include('backender.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

game/urls.py
from django.urls import path
from . import views
app_name = 'game'

urlpatterns = [
    path('', views.index, name='index'),
    path('test', views.test, name='test'),
]

leaderboard/urls.py
from django.urls import path
from . import views
app_name = 'leaderboard'

urlpatterns = [


    # API
    path('api/record/', views.RecordView.as_view(), name='record')
]

town/urls.py
from django.urls import path
from . import views


app_name = 'town'

urlpatterns = [
    path('', views.index, name='index'),
]

wordle/urls.py
from django.urls import path
from . import views
app_name = 'wordle'

urlpatterns = [
    path('', views.index, name='main'),
    path('stats', views.stats, name='stats'),
    path('leaderboard', views.leaderboard, name='leaderboard'),

    # API
    path('api/', views.WordAPIView.as_view(), name='word')
]

leaderboard/models.py
from django.db import models
from accounts.models import User
from wordle.models import Word

class Record(models.Model):
    word = models.ForeignKey(Word, db_column="word", on_delete=models.CASCADE, null=False)
    result = models.BooleanField(null=True)
    tries = models.PositiveSmallIntegerField(null=True)
    user = models.ForeignKey(User, db_column="user", on_delete=models.DO_NOTHING, null=True)
    time = models.DateTimeField(auto_now=True, null=True)
    guess1 = models.CharField(max_length=5, null=True)
    guess2 = models.CharField(max_length=5, null=True)
    guess3 = models.CharField(max_length=5, null=True)
    guess4 = models.CharField(max_length=5, null=True)
    guess5 = models.CharField(max_length=5, null=True)
    guess6 = models.CharField(max_length=5, null=True)

wordle/models.py
from django.db import models

class Word(models.Model):
    word = models.CharField(max_length=5)
    def __str__(self):
        return self.word

leaderboard/views.py
import jwt

from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from .serializer import RecordSerializer

# from config.settings.base import SECRET_KEY

from django.shortcuts import get_object_or_404

from accounts.models import User
from accounts.serializer import UserSerializer


class RecordView(APIView):

    def post(self, request):
        try:
            user_id = request.data.get('user')
            if user_id :
                try:
                    user = User.objects.get(pk=user_id)
                except User.DoesNotExist:
                    return Response(status=status.HTTP_404_NOT_FOUND)
                
                user.plays += 1
                
                if request.data.get('result'):
                    tries = request.data.get('tries')
                    user.tries += tries
                    user.wins += 1
                
                user.save()

            serializer = RecordSerializer(data=request.data)
            if serializer.is_valid():
                serializer.save()
                return Response(status=status.HTTP_200_OK)
            
            return Response(status=status.HTTP_400_BAD_REQUEST)

        except:
            return Response(status=status.HTTP_400_BAD_REQUEST)

wordle/views.py
import random

from django.shortcuts   import render
from django.http        import HttpResponse
from django.core        import serializers

from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response

from .models import Word

from .serializer import WordSerializer

def index(request): # 게임 페이지
    return render(request, 'wordle/main.html') 

def stats(request): # 통계 페이지로
    return render(request, 'wordle/stats.html') 

def leaderboard(request): # 리더보드 페이지
    return render(request, 'wordle/leaderboard.html') 

class WordAPIView(APIView):
    
    serializer_class = WordSerializer

    def get(self, request):
        
        if request.query_params:
            id = request.query_params.get('id', None)
            rand = request.query_params.get('rand', None)
            word = request.query_params.get('word', None)

            if id: # 아이디에 해당하는 단어 리턴
                try:
                    queryset = Word.objects.get(id=id)
                    rt_word = queryset.word
                    return Response(data=rt_word, status=status.HTTP_200_OK)
                except:
                    return Response(status=status.HTTP_404_NOT_FOUND)
            
            elif rand: # 무작위 단어 리턴
                total = Word.objects.count()
                rand_id = random.randrange(1,total)   
                queryset = Word.objects.get(id=rand_id)
                rt_word = queryset.word
                data = {'word':rt_word, 'id':rand_id}
                return Response(data=data, status=status.HTTP_200_OK)
            
            elif word: # 단어 데이터베이스에 있는지 체크
                try:
                    queryset = Word.objects.get(word=word)
                    return Response(data=True, status=status.HTTP_200_OK)
                except:
                    return Response(data=False, status=status.HTTP_200_OK)
                

            return Response(status=status.HTTP_400_BAD_REQUEST)
    

templates/wordle/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div id="container">
    <div id="game">
        <header>
            <h1 class="title">WORDLE</h1>
        </header>
        <!-- <a href="javascript:openPop()">
            <div>box</div>
        </a> -->
        
        <!-- <div id="result-box" class="modal-window" style="display: none;"></div> -->
        <div id="result-box" class="modal hidden">
            <div class="bg"></div>
            <div id="result" class="modal-box">
                <div id="result-content"></div>
                <div class="btn-container">
                    <button class="result-btn newgame" id="btn-newgame" onclick="newGame()">new game</button>
                    <button class="result-btn exit">exit</button>
                </div>
            </div>
        </div>

        <div id="board-container">
            <div id="board"></div>
        </div>
        <div id="keyboard-container">
            <div class="keyboard-row">
                <button data-key="q">q</button>
                <button data-key="w">w</button>
                <button data-key="e">e</button>
                <button data-key="r">r</button>
                <button data-key="t">t</button>
                <button data-key="y">y</button>
                <button data-key="u">u</button>
                <button data-key="i">i</button>
                <button data-key="o">o</button>
                <button data-key="p">p</button>
            </div>
            <div class="keyboard-row">
                <div class="spacer-half"></div>
                <button data-key="a">a</button>
                <button data-key="s">s</button>
                <button data-key="d">d</button>
                <button data-key="f">f</button>
                <button data-key="g">g</button>
                <button data-key="h">h</button>
                <button data-key="j">j</button>
                <button data-key="k">k</button>
                <button data-key="l">l</button>
                <div class="spacer-half"></div>
            </div>
            <div class="keyboard-row">
                <button data-key="enter" class="wide-button">Enter</button>
                <button data-key="z">z</button>
                <button data-key="x">x</button>
                <button data-key="c">c</button>
                <button data-key="v">v</button>
                <button data-key="b">b</button>
                <button data-key="n">n</button>
                <button data-key="m">m</button>
                <button data-key="del" class="wide-button">Del</button>
            </div>
        </div>
        <div id="word-container">
            <div id="words"></div>
        </div>
    </div>
</div>
<script type="text/javascript" src="{% static 'js/wordle.js' %}"> </script>
{% endblock %}

templates/wordle/leaderboard.html
{% load static %}
<!doctype html>
<html lang="ko">

<head>
    <title>Wordle - Stats</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{% static 'img/favicon_wordle(32x32).png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/wordle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
</head>

<body>
    <div id="container">
        <header>
            {% include 'sidemenu.html' %}

            <h1 class="title">WORDLE</h1>

            <div id="user-menu" class="user-popup">
                <a id="user-info" class="user-popup-trigger" onclick="userInfo()">&#128100; Log In</a>
                <div class="user-popup-content">
                    <a href="{% url 'accounts:setting' %}">Settings</a>
                    <a onclick="userLogout()">Logout</a>
                </div>
            </div>
        </header>

        <iframe width="100%" height="1080" src="https://lookerstudio.google.com/embed/reporting/8e19475f-70e6-4bd9-a80b-8e9219b11ba0/page/mhsND" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
    <script type="text/javascript" src="{% static 'js/userinfo.js' %}"> </script>
</body>

</html>

templates/wordle/main.html
{% load static %}
<!doctype html>
<html lang="ko">

<head>
    <title>Wordle</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{% static 'img/favicon_wordle(32x32).png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/wordle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
</head>

<body>
    <div id="container">
        <header>
            {% include 'sidemenu.html' %}
            
            <h1 class="title">WORDLE</h1>
    
            <div id="user-menu" class="user-popup">
                <a id="user-info" class="user-popup-trigger" onclick="userInfo()">&#128100; Log In</a>
                <div class="user-popup-content">
                    <a href="{% url 'accounts:setting' %}">Settings</a>
                    <a onclick="userLogout()">Logout</a>
                </div>
            </div>
        </header>

        <div id="game">
            <div id="result-box" class="modal hidden">
                <div class="bg"></div>
                <div id="result" class="modal-box">
                    <div id="result-content"></div>
                    <div class="btn-container">
                        <button class="result-btn newgame" id="btn-newgame" onclick="newGame()">NEW GAME</button>
                        <!-- <a id="btn-stats" class="button" href="{% url 'wordle:stats' %}">Stats</a> -->
                        <!-- <a id="btn-town" class="button" href="{% url 'town:index' %}">TOWN</a> -->
                    </div>
                </div>
            </div>

            <div id="board-container">
                <div id="board"></div>
            </div>
            <div id="keyboard-container">
                <div class="keyboard-row">
                    <button data-key="q">q</button>
                    <button data-key="w">w</button>
                    <button data-key="e">e</button>
                    <button data-key="r">r</button>
                    <button data-key="t">t</button>
                    <button data-key="y">y</button>
                    <button data-key="u">u</button>
                    <button data-key="i">i</button>
                    <button data-key="o">o</button>
                    <button data-key="p">p</button>
                </div>
                <div class="keyboard-row">
                    <div class="spacer-half"></div>
                    <button data-key="a">a</button>
                    <button data-key="s">s</button>
                    <button data-key="d">d</button>
                    <button data-key="f">f</button>
                    <button data-key="g">g</button>
                    <button data-key="h">h</button>
                    <button data-key="j">j</button>
                    <button data-key="k">k</button>
                    <button data-key="l">l</button>
                    <div class="spacer-half"></div>
                </div>
                <div class="keyboard-row">
                    <button data-key="enter" class="wide-button">Enter</button>
                    <button data-key="z">z</button>
                    <button data-key="x">x</button>
                    <button data-key="c">c</button>
                    <button data-key="v">v</button>
                    <button data-key="b">b</button>
                    <button data-key="n">n</button>
                    <button data-key="m">m</button>
                    <button data-key="del" class="wide-button">Del</button>
                </div>
            </div>
            <div id="word-container">
                <div id="words"></div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'js/userinfo.js' %}"> </script>
    <script type="text/javascript" src="{% static 'js/wordle.js' %}"> </script>
</body>

</html>

templates/wordle/stats.html
{% load static %}
<!doctype html>
<html lang="ko">

<head>
    <title>Wordle - Stats</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{% static 'img/favicon_wordle(32x32).png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/wordle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
</head>

<body>
    <div id="container">
        <header>
            {% include 'sidemenu.html' %}

            <h1 class="title">WORDLE</h1>

            <div id="user-menu" class="user-popup">
                <a id="user-info" class="user-popup-trigger" onclick="userInfo()">&#128100; Log In</a>
                <div class="user-popup-content">
                    <a href="{% url 'accounts:setting' %}">Settings</a>
                    <a onclick="userLogout()">Logout</a>
                </div>
            </div>
        </header>

        <iframe width="100%" height="1080" src="https://lookerstudio.google.com/embed/reporting/2721fc8f-b1d8-4644-82cb-d4f56cbdc67b/page/mhsND" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
    <script type="text/javascript" src="{% static 'js/userinfo.js' %}"> </script>
</body>

</html>