config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('wordle/', include('wordle.urls')),
    path('accounts/', include('accounts.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('', include('town.urls')),
    path('backender/', include('backender.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

game/urls.py
from django.urls import path
from . import views
app_name = 'game'

urlpatterns = [
    path('', views.index, name='index'),
    path('test', views.test, name='test'),
]

town/urls.py
from django.urls import path
from . import views


app_name = 'town'

urlpatterns = [
    path('', views.index, name='index'),
]

wordle/urls.py
from django.urls import path
from . import views
app_name = 'wordle'

urlpatterns = [
    path('', views.index, name='main'),
    path('stats', views.stats, name='stats'),
    path('leaderboard', views.leaderboard, name='leaderboard'),

    # API
    path('api/', views.WordAPIView.as_view(), name='word')
]

templates/sidemenu.html
<div id="side-menu" class="side-menu">
    <a href="javascript:void(0)" class="close-btn" onclick="closeSlideMenu()">&times;</a>
    <h2>Menu</h2>
    <br>
    <a href="{% url 'wordle:main' %}">&#9989; Wordle</a>
    <a href="{% url 'wordle:stats' %}">&#128202; Stats</a>
    <a href="{% url 'wordle:leaderboard' %}">&#127941; Leaderboard</a>
    <!-- <a href="#">&#128292; Words</a> -->
    <a href="{% url 'town:index' %}">&#127750; Town</a>
</div>
<div id="menu">
    <a class="menu-icon" onclick="openSlideMenu()">&#9776; Menu</a>
</div>